---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GithubOauthToken:
    Type: String
Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: BucketOwnerFullControl
  BuildAndDeployFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: react-boilerplate-ci
      RoleArn:
        Fn::GetAtt:
          - PipelineRole
          - Arn
      ArtifactStore:
        Location:
          Ref:
            ArtifactStoreBucket
        Type: S3
      Stages:
        - Name: source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: myapp
              Configuration:
                Owner: s0enke
                Repo: react-boilerplate
                Branch: master
                OAuthToken:
                  Ref: GithubOauthToken
              RunOrder: 1
        - Name: build_and_deploy
          Actions:
            - InputArtifacts: []
              Name: Lambda
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              OutputArtifacts: []
              Configuration:
                FunctionName:
                  Ref: BuildAndDeployFunction
              RunOrder: 2
  BuildAndDeployFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event, context):
            pass
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - BuildAndDeployFunctionRole
          - Arn
      Runtime: python2.7


